site_name: 'ğŸ›°ï¸ 01: Echoes Lost in Orbit'

nav:
  - Introduction: index.md
  - 'ğŸŸ¢ Beginner': beginner.md
  - 'ğŸŸ¡ Intermediate': intermediate.md
  - 'Solutions':
      - 'ğŸŸ¢ Beginner': solutions/beginner.md
      - 'ğŸŸ¡ Intermediate': solutions/intermediate.md
